### ISSUE TITLE
how to plot a line chart in an x-y coordinate

### ISSUE THREAD

**Issue by SlumDunk** [jpkli/p4.gl#2]
I want to know how to plot a line chart use P4, I don't find any example in your github, thank you!

**Comment by jpkli** [comment]
Hi @SlumDunk, very sorry that the development and documentation of P4 were suspended last year, but I have resumed the development of P4 and trying to make it more useful for processing and visualizing large data on the web. The examples and updated documentation can be found in [here](https://jpkli.github.io/p4). I am going to close this issue. If you still want to try the library for future projects, please let me know any problems or comments in [this discussion group](https://groups.google.com/forum/#!forum/p4js) . Thank you.
